In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data=pd.read_csv('Transformed_data.csv')

In [3]:
data.drop('Unnamed: 0',axis=1,inplace = True)

In [4]:
data

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category,Group
0,58,management,married,tertiary,unknown,5,may,261,1,unknown,no,56-60,1
1,44,technician,single,secondary,unknown,5,may,151,1,unknown,no,41-45,1
2,33,entrepreneur,married,secondary,unknown,5,may,76,1,unknown,no,31-35,1
3,47,blue-collar,married,primary,unknown,5,may,92,1,unknown,no,46-50,1
4,33,unknown,single,unknown,unknown,5,may,198,1,unknown,no,31-35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45154,51,technician,married,secondary,cellular,17,apr,977,3,unknown,yes,51-55,1
45155,71,retired,divorced,primary,cellular,17,apr,456,2,unknown,yes,71-75,1
45156,72,retired,married,secondary,cellular,17,apr,1127,5,success,yes,71-75,1
45157,57,blue-collar,married,secondary,telephone,17,apr,508,4,unknown,no,56-60,1
45158,37,entrepreneur,married,secondary,cellular,17,nov,361,2,unknown,no,36-40,1

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 13 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45159 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      45159 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 45159 non-null  object
 7   Contact Duration (Seconds)                     45159 non-null  int64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         45159 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
 12  Group                                          45159 non-null  int64
dtypes: int64(5), object(8)
memory usage: 4.5+ MB

In [6]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', 'primary', 'unknown'], dtype=object)

In [7]:
data.loc[(data['Subscription Status']=='no') & (data['Educational Qualification'].isnull())]

Empty DataFrame
Columns: [Age, Job, Marital Status, Educational Qualification, Contact Communication type, Last Contact Day Of The Month, Last Contact Month Of The Year, Contact Duration (Seconds), No Of Contacts Performed During This Campaign, Outcome Of Previous Marketing Campaign, Subscription Status, Age_Category, Group]
Index: []

In [8]:
data.columns

Index(['Age', 'Job', 'Marital Status', 'Educational Qualification',
       'Contact Communication type', 'Last Contact Day Of The Month',
       'Last Contact Month Of The Year', 'Contact Duration (Seconds)',
       'No Of Contacts Performed During This Campaign',
       'Outcome Of Previous Marketing Campaign', 'Subscription Status',
       'Age_Category', 'Group'],
      dtype='object')

In [9]:
new_data=data[['Job','Marital Status','Educational Qualification','Subscription Status','Outcome Of Previous Marketing Campaign']]
new_data=new_data.loc[new_data['Educational Qualification'].notnull()]
new_data['Group']=1

In [10]:
new_data

,Job,Marital Status,Educational Qualification,Subscription Status,Outcome Of Previous Marketing Campaign,Group
0,management,married,tertiary,no,unknown,1
1,technician,single,secondary,no,unknown,1
2,entrepreneur,married,secondary,no,unknown,1
3,blue-collar,married,primary,no,unknown,1
4,unknown,single,unknown,no,unknown,1
...,...,...,...,...,...,...
45154,technician,married,secondary,yes,unknown,1
45155,retired,divorced,primary,yes,unknown,1
45156,retired,married,secondary,yes,success,1
45157,blue-collar,married,secondary,no,unknown,1
45158,entrepreneur,married,secondary,no,unknown,1

In [11]:
n1=pd.DataFrame(new_data.groupby(['Job','Marital Status','Subscription Status','Outcome Of Previous Marketing Campaign','Educational Qualification']).count())
n1.reset_index(inplace=True)
n1

,Job,Marital Status,Subscription Status,Outcome Of Previous Marketing Campaign,Educational Qualification,Group
0,admin.,divorced,no,failure,primary,1
1,admin.,divorced,no,failure,secondary,39
2,admin.,divorced,no,failure,tertiary,4
3,admin.,divorced,no,failure,unknown,1
4,admin.,divorced,no,other,primary,1
...,...,...,...,...,...,...
717,unknown,single,yes,failure,secondary,1
718,unknown,single,yes,success,secondary,1
719,unknown,single,yes,unknown,secondary,2
720,unknown,single,yes,unknown,tertiary,2
721,unknown,single,yes,unknown,unknown,2

In [12]:
n1['Job'].unique()

array(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'unknown'], dtype=object)

In [13]:
n1['Marital Status'].unique()

array(['divorced', 'married', 'single'], dtype=object)

# Code For Filling NA Of Educational Qualification

In [15]:
'''
n2=n1.loc[(n1['Job']=='unknown') & (n1['Subscription Status']=='yes')]
Marital_Status=n2.loc[n2['Marital Status']=='divorced']
Marital_Status
'''

"\nn2=n1.loc[(n1['Job']=='unknown') & (n1['Subscription Status']=='yes')]\nMarital_Status=n2.loc[n2['Marital Status']=='divorced']\nMarital_Status\n"

In [16]:
'''
data.loc[(data['Job']=='unknown')  
#& (data['Marital Status']=='divorced') 
#& (data['Subscription Status']=='no') 
#& (data['Outcome Of Previous Marketing Campaign'].isin(['unknown']))
#& (data['Outcome Of Previous Marketing Campaign'].isnull())
,'Educational Qualification']=data.fillna('secondary')
'''

"\ndata.loc[(data['Job']=='unknown')  \n#& (data['Marital Status']=='divorced') \n#& (data['Subscription Status']=='no') \n#& (data['Outcome Of Previous Marketing Campaign'].isin(['unknown']))\n#& (data['Outcome Of Previous Marketing Campaign'].isnull())\n,'Educational Qualification']=data.fillna('secondary')\n"

In [17]:
'''
data.loc[(data['Job']=='unknown')  
& (data['Educational Qualification'].isnull())]
'''

"\ndata.loc[(data['Job']=='unknown')  \n& (data['Educational Qualification'].isnull())]\n"

In [18]:
'''
data.loc[(data['Job']=='unknown')  
#& (data['Educational Qualification'].isnull())]
& (data['Marital Status']=='single')
& (data['Subscription Status']=='yes') & (data['Outcome Of Previous Marketing Campaign'].isnull())]['Educational Qualification'].value_counts()
#& (data['Outcome Of Previous Marketing Campaign']=='other')]['Educational Qualification'].value_counts()
#]['Educational Qualification'].value_counts()
'''

"\ndata.loc[(data['Job']=='unknown')  \n#& (data['Educational Qualification'].isnull())]\n& (data['Marital Status']=='single')\n& (data['Subscription Status']=='yes') & (data['Outcome Of Previous Marketing Campaign'].isnull())]['Educational Qualification'].value_counts()\n#& (data['Outcome Of Previous Marketing Campaign']=='other')]['Educational Qualification'].value_counts()\n#]['Educational Qualification'].value_counts()\n"

In [19]:
'''
data.loc[(data['Job']=='housemaid')  
& (data['Educational Qualification'].isnull())
& (data['Subscription Status']=='no')]

'''

"\ndata.loc[(data['Job']=='housemaid')  \n& (data['Educational Qualification'].isnull())\n& (data['Subscription Status']=='no')]\n\n"

# Code For Filling NA For Outcome OF Previous Marketing Campaign

In [21]:
data

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category,Group
0,58,management,married,tertiary,unknown,5,may,261,1,unknown,no,56-60,1
1,44,technician,single,secondary,unknown,5,may,151,1,unknown,no,41-45,1
2,33,entrepreneur,married,secondary,unknown,5,may,76,1,unknown,no,31-35,1
3,47,blue-collar,married,primary,unknown,5,may,92,1,unknown,no,46-50,1
4,33,unknown,single,unknown,unknown,5,may,198,1,unknown,no,31-35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45154,51,technician,married,secondary,cellular,17,apr,977,3,unknown,yes,51-55,1
45155,71,retired,divorced,primary,cellular,17,apr,456,2,unknown,yes,71-75,1
45156,72,retired,married,secondary,cellular,17,apr,1127,5,success,yes,71-75,1
45157,57,blue-collar,married,secondary,telephone,17,apr,508,4,unknown,no,56-60,1
45158,37,entrepreneur,married,secondary,cellular,17,nov,361,2,unknown,no,36-40,1

In [22]:
data.columns

Index(['Age', 'Job', 'Marital Status', 'Educational Qualification',
       'Contact Communication type', 'Last Contact Day Of The Month',
       'Last Contact Month Of The Year', 'Contact Duration (Seconds)',
       'No Of Contacts Performed During This Campaign',
       'Outcome Of Previous Marketing Campaign', 'Subscription Status',
       'Age_Category', 'Group'],
      dtype='object')

In [23]:
data['Group'] = 1

In [24]:
n3=pd.DataFrame(data.groupby(['Job','Marital Status','Contact Communication type','Subscription Status','Outcome Of Previous Marketing Campaign'])['Group'].count())

In [25]:
n3.reset_index(inplace = True)

In [26]:
n3

,Job,Marital Status,Contact Communication type,Subscription Status,Outcome Of Previous Marketing Campaign,Group
0,admin.,divorced,cellular,no,failure,43
1,admin.,divorced,cellular,no,other,18
2,admin.,divorced,cellular,no,success,10
3,admin.,divorced,cellular,no,unknown,230
4,admin.,divorced,cellular,yes,failure,6
...,...,...,...,...,...,...
520,unknown,single,cellular,yes,success,1
521,unknown,single,cellular,yes,unknown,5
522,unknown,single,telephone,no,unknown,7
523,unknown,single,telephone,yes,unknown,1
524,unknown,single,unknown,no,unknown,26

In [27]:
n3['Job'].unique()

array(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'unknown'], dtype=object)

In [28]:
n3['Marital Status'].unique()

array(['divorced', 'married', 'single'], dtype=object)

In [29]:
n3['Contact Communication type'].unique()

array(['cellular', 'telephone', 'unknown'], dtype=object)

In [30]:
n3['Subscription Status'].unique()

array(['no', 'yes'], dtype=object)

In [31]:
'''
Job=n3.loc[(n3['Job']=='entrepreneur') & (n3['Marital Status']=='divorced')]
Marital_Status = Job.loc[(Job['Contact Communication type']=='unknown') & (Job['Subscription Status']=='yes')]
Marital_Status
'''

"\nJob=n3.loc[(n3['Job']=='entrepreneur') & (n3['Marital Status']=='divorced')]\nMarital_Status = Job.loc[(Job['Contact Communication type']=='unknown') & (Job['Subscription Status']=='yes')]\nMarital_Status\n"

In [32]:
'''
data.loc[
(data['Job']=='entrepreneur')
&(data['Marital Status']=='single')
&(data['Contact Communication type']=='unknown')
&(data['Subscription Status']=='no')
,'Outcome Of Previous Marketing Campaign'
]=data.fillna('unknown')
'''

"\ndata.loc[\n(data['Job']=='entrepreneur')\n&(data['Marital Status']=='single')\n&(data['Contact Communication type']=='unknown')\n&(data['Subscription Status']=='no')\n,'Outcome Of Previous Marketing Campaign'\n]=data.fillna('unknown')\n"

In [33]:
'''
new=pd.DataFrame(
data.loc[
#(data['Contact Communication type']=='cellular') 
 (data['Outcome Of Previous Marketing Campaign'].isnull()) 
& (data['Job']=='entrepreneur')])

new
'''

"\nnew=pd.DataFrame(\ndata.loc[\n#(data['Contact Communication type']=='cellular') \n (data['Outcome Of Previous Marketing Campaign'].isnull()) \n& (data['Job']=='entrepreneur')])\n\nnew\n"

# Code For Filling NA For Contact Duration (Seconds)

In [35]:
data

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category,Group
0,58,management,married,tertiary,unknown,5,may,261,1,unknown,no,56-60,1
1,44,technician,single,secondary,unknown,5,may,151,1,unknown,no,41-45,1
2,33,entrepreneur,married,secondary,unknown,5,may,76,1,unknown,no,31-35,1
3,47,blue-collar,married,primary,unknown,5,may,92,1,unknown,no,46-50,1
4,33,unknown,single,unknown,unknown,5,may,198,1,unknown,no,31-35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45154,51,technician,married,secondary,cellular,17,apr,977,3,unknown,yes,51-55,1
45155,71,retired,divorced,primary,cellular,17,apr,456,2,unknown,yes,71-75,1
45156,72,retired,married,secondary,cellular,17,apr,1127,5,success,yes,71-75,1
45157,57,blue-collar,married,secondary,telephone,17,apr,508,4,unknown,no,56-60,1
45158,37,entrepreneur,married,secondary,cellular,17,nov,361,2,unknown,no,36-40,1

In [36]:
data.columns

Index(['Age', 'Job', 'Marital Status', 'Educational Qualification',
       'Contact Communication type', 'Last Contact Day Of The Month',
       'Last Contact Month Of The Year', 'Contact Duration (Seconds)',
       'No Of Contacts Performed During This Campaign',
       'Outcome Of Previous Marketing Campaign', 'Subscription Status',
       'Age_Category', 'Group'],
      dtype='object')

In [37]:
n4=data[['Job', 'Marital Status','Contact Communication type', 'Subscription Status','Contact Duration (Seconds)']]

In [38]:
n4=n4.loc[n4['Contact Duration (Seconds)'].notnull()]
n4

,Job,Marital Status,Contact Communication type,Subscription Status,Contact Duration (Seconds)
0,management,married,unknown,no,261
1,technician,single,unknown,no,151
2,entrepreneur,married,unknown,no,76
3,blue-collar,married,unknown,no,92
4,unknown,single,unknown,no,198
...,...,...,...,...,...
45154,technician,married,cellular,yes,977
45155,retired,divorced,cellular,yes,456
45156,retired,married,cellular,yes,1127
45157,blue-collar,married,telephone,no,508
45158,entrepreneur,married,cellular,no,361

In [39]:
contact=pd.DataFrame(n4.groupby(['Job', 'Marital Status','Contact Communication type', 'Subscription Status'])['Contact Duration (Seconds)'].median())

contact.reset_index(inplace = True)

contact

,Job,Marital Status,Contact Communication type,Subscription Status,Contact Duration (Seconds)
0,admin.,divorced,cellular,no,155.0
1,admin.,divorced,cellular,yes,503.0
2,admin.,divorced,telephone,no,204.0
3,admin.,divorced,telephone,yes,357.0
4,admin.,divorced,unknown,no,169.0
...,...,...,...,...,...
201,unknown,single,cellular,no,144.0
202,unknown,single,cellular,yes,438.0
203,unknown,single,telephone,no,96.0
204,unknown,single,telephone,yes,232.0
205,unknown,single,unknown,no,156.0

In [40]:
contact['Job'].unique()

array(['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management',
       'retired', 'self-employed', 'services', 'student', 'technician',
       'unemployed', 'unknown'], dtype=object)

In [41]:
contact['Marital Status'].unique()

array(['divorced', 'married', 'single'], dtype=object)

In [42]:
contact['Contact Communication type'].unique()

array(['cellular', 'telephone', 'unknown'], dtype=object)

In [43]:
'''
Job=contact.loc[(contact['Job'].isin(['entrepreneur'])) & (contact['Marital Status']=='single')
& (contact['Contact Communication type']=='telephone') ]
Job
'''

"\nJob=contact.loc[(contact['Job'].isin(['entrepreneur'])) & (contact['Marital Status']=='single')\n& (contact['Contact Communication type']=='telephone') ]\nJob\n"

In [44]:
'''
data.loc[(data['Job']=='entrepreneur') 
& (data['Marital Status']=='divorced') 
& (data['Contact Communication type']=='telephone') 
& (data['Subscription Status']=='no')
,'Contact Duration (Seconds)']=data.fillna(301)
'''

"\ndata.loc[(data['Job']=='entrepreneur') \n& (data['Marital Status']=='divorced') \n& (data['Contact Communication type']=='telephone') \n& (data['Subscription Status']=='no')\n,'Contact Duration (Seconds)']=data.fillna(301)\n"

In [45]:
'''
data.loc[(data['Job']=='entrepreneur') 
& (data['Marital Status']=='single') 
& (data['Contact Communication type']=='telephone') 
& (data['Subscription Status']=='yes')
,'Contact Duration (Seconds)']=data.fillna(114)
'''

"\ndata.loc[(data['Job']=='entrepreneur') \n& (data['Marital Status']=='single') \n& (data['Contact Communication type']=='telephone') \n& (data['Subscription Status']=='yes')\n,'Contact Duration (Seconds)']=data.fillna(114)\n"

# Code For Filling NA For Last Contact Month Of The Year

In [46]:
data

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category,Group
0,58,management,married,tertiary,unknown,5,may,261,1,unknown,no,56-60,1
1,44,technician,single,secondary,unknown,5,may,151,1,unknown,no,41-45,1
2,33,entrepreneur,married,secondary,unknown,5,may,76,1,unknown,no,31-35,1
3,47,blue-collar,married,primary,unknown,5,may,92,1,unknown,no,46-50,1
4,33,unknown,single,unknown,unknown,5,may,198,1,unknown,no,31-35,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45154,51,technician,married,secondary,cellular,17,apr,977,3,unknown,yes,51-55,1
45155,71,retired,divorced,primary,cellular,17,apr,456,2,unknown,yes,71-75,1
45156,72,retired,married,secondary,cellular,17,apr,1127,5,success,yes,71-75,1
45157,57,blue-collar,married,secondary,telephone,17,apr,508,4,unknown,no,56-60,1
45158,37,entrepreneur,married,secondary,cellular,17,nov,361,2,unknown,no,36-40,1

In [47]:
data.columns

Index(['Age', 'Job', 'Marital Status', 'Educational Qualification',
       'Contact Communication type', 'Last Contact Day Of The Month',
       'Last Contact Month Of The Year', 'Contact Duration (Seconds)',
       'No Of Contacts Performed During This Campaign',
       'Outcome Of Previous Marketing Campaign', 'Subscription Status',
       'Age_Category', 'Group'],
      dtype='object')

In [48]:
'''
new=data[['Last Contact Day Of The Month',
       'Last Contact Month Of The Year',
        'Subscription Status']]
new=pd.DataFrame(new.groupby(['Last Contact Day Of The Month','Subscription Status'])['Last Contact Month Of The Year'].value_counts())
new=new.reset_index()
new
'''

"\nnew=data[['Last Contact Day Of The Month',\n       'Last Contact Month Of The Year',\n        'Subscription Status']]\nnew=pd.DataFrame(new.groupby(['Last Contact Day Of The Month','Subscription Status'])['Last Contact Month Of The Year'].value_counts())\nnew=new.reset_index()\nnew\n"

In [49]:
'''
new.loc[((new['Last Contact Day Of The Month'])==31)]
'''

"\nnew.loc[((new['Last Contact Day Of The Month'])==31)]\n"

In [50]:
'''
data.loc[
(data['Last Contact Day Of The Month']==31) 
& (data['Subscription Status']=='no')
,'Last Contact Month Of The Year'
]=data.fillna('jul')
'''

"\ndata.loc[\n(data['Last Contact Day Of The Month']==31) \n& (data['Subscription Status']=='no')\n,'Last Contact Month Of The Year'\n]=data.fillna('jul')\n"

In [51]:
'''
data.loc[
(data['Last Contact Day Of The Month']==31) 
& (data['Subscription Status']=='yes')
,'Last Contact Month Of The Year'
]=data.fillna('jul')
'''

"\ndata.loc[\n(data['Last Contact Day Of The Month']==31) \n& (data['Subscription Status']=='yes')\n,'Last Contact Month Of The Year'\n]=data.fillna('jul')\n"

In [126]:
Eda_Data=data.copy()
Model_Data=data.copy()

In [52]:
'''
data.to_csv('Transformed_data.csv')
'''

"\ndata.to_csv('Transformed_data.csv')\n"

In [130]:
'''
Eda_Data.to_csv('Eda_Data.csv')
Model_Data.to_csv('Model_Data.csv')
'''