In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
data=pd.read_csv('Transformed_data.csv')
data

,Unnamed: 0,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category
0,0,58,management,married,tertiary,unknown,5,NaN,261.0,1,NaN,no,56-60
1,1,44,technician,single,secondary,unknown,5,NaN,151.0,1,unknown,no,41-45
2,2,33,entrepreneur,married,secondary,unknown,5,may,76.0,1,unknown,no,31-35
3,3,47,blue-collar,married,NaN,unknown,5,NaN,92.0,1,unknown,no,46-50
4,4,33,unknown,single,unknown,unknown,5,may,198.0,1,unknown,no,31-35
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45154,45206,51,technician,married,NaN,cellular,17,NaN,977.0,3,NaN,yes,51-55
45155,45207,71,retired,divorced,primary,cellular,17,NaN,456.0,2,unknown,yes,71-75
45156,45208,72,retired,married,NaN,cellular,17,NaN,1127.0,5,success,yes,71-75
45157,45209,57,blue-collar,married,secondary,telephone,17,NaN,508.0,4,unknown,no,56-60
45158,45210,37,entrepreneur,married,secondary,cellular,17,nov,361.0,2,NaN,no,36-40

In [3]:
data.drop(['Unnamed: 0'],axis=1,inplace = True)

In [4]:
data

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category
0,58,management,married,tertiary,unknown,5,NaN,261.0,1,NaN,no,56-60
1,44,technician,single,secondary,unknown,5,NaN,151.0,1,unknown,no,41-45
2,33,entrepreneur,married,secondary,unknown,5,may,76.0,1,unknown,no,31-35
3,47,blue-collar,married,NaN,unknown,5,NaN,92.0,1,unknown,no,46-50
4,33,unknown,single,unknown,unknown,5,may,198.0,1,unknown,no,31-35
...,...,...,...,...,...,...,...,...,...,...,...,...
45154,51,technician,married,NaN,cellular,17,NaN,977.0,3,NaN,yes,51-55
45155,71,retired,divorced,primary,cellular,17,NaN,456.0,2,unknown,yes,71-75
45156,72,retired,married,NaN,cellular,17,NaN,1127.0,5,success,yes,71-75
45157,57,blue-collar,married,secondary,telephone,17,NaN,508.0,4,unknown,no,56-60
45158,37,entrepreneur,married,secondary,cellular,17,nov,361.0,2,NaN,no,36-40

In [5]:
married_secondary_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [6]:
married_secondary_unknown_yes['Job'].value_counts()

Job
technician       66
blue-collar      65
admin.           49
services         38
management       15
unemployed        9
retired           7
self-employed     7
entrepreneur      7
housemaid         4
student           1
Name: count, dtype: int64

In [7]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('technician')

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44640 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [9]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [10]:
married_tertiary_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [11]:
married_tertiary_unknown_yes['Job'].value_counts()

Job
management       95
technician       31
entrepreneur     13
self-employed     8
admin.            7
retired           2
unemployed        2
blue-collar       1
services          1
Name: count, dtype: int64

In [12]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('management')

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44706 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [14]:
married_null_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [15]:
married_null_unknown_yes['Job'].value_counts()

Job
blue-collar      43
management       43
technician       26
admin.           18
services         12
entrepreneur      9
self-employed     8
housemaid         4
unemployed        3
retired           3
Name: count, dtype: int64

In [16]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('blue-collar')

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44750 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [18]:
married_unknown_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [19]:
married_unknown_unknown_yes['Job'].value_counts()

Job
management       7
blue-collar      3
services         3
technician       3
retired          1
self-employed    1
admin.           1
unknown          1
Name: count, dtype: int64

In [20]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('management')

In [21]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44760 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [22]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [23]:
married_primary_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [24]:
married_primary_unknown_yes['Job'].value_counts()

Job
blue-collar     33
housemaid        7
services         5
management       5
entrepreneur     4
retired          3
technician       3
unknown          2
unemployed       2
admin.           2
Name: count, dtype: int64

In [25]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('blue-collar')

In [26]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44784 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [27]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [28]:
married_secondary_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [29]:
married_secondary_null_yes['Job'].value_counts()

Job
technician       31
admin.           29
blue-collar      25
services         16
management        5
housemaid         3
self-employed     3
unemployed        3
retired           3
entrepreneur      2
unknown           1
student           1
Name: count, dtype: int64

In [30]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('technician')

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44830 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [32]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [33]:
married_tertiary_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [34]:
married_tertiary_null_yes['Job'].value_counts()

Job
management       67
technician       19
admin.            5
retired           2
self-employed     1
unemployed        1
services          1
Name: count, dtype: int64

In [35]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('management')

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44860 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [37]:
married_null_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [38]:
married_null_null_yes['Job'].value_counts()

Job
management       29
blue-collar      16
technician       14
admin.           11
housemaid         6
services          6
self-employed     4
unemployed        2
entrepreneur      1
retired           1
unknown           1
Name: count, dtype: int64

In [39]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('management')

In [40]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44895 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [41]:
married_unknown_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [42]:
married_unknown_null_yes['Job'].value_counts()

Job
blue-collar    4
housemaid      1
retired        1
admin.         1
management     1
technician     1
Name: count, dtype: int64

In [43]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('blue-collar')

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44901 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [45]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [46]:
married_primary_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [47]:
married_primary_null_yes['Job'].value_counts()

Job
blue-collar     17
unemployed       5
services         4
management       4
retired          3
housemaid        1
entrepreneur     1
technician       1
Name: count, dtype: int64

In [48]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('blue-collar')

In [49]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44912 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [50]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [51]:
married_secondary_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [52]:
married_secondary_failure_yes['Job'].value_counts()

Job
blue-collar      12
technician       10
services          9
admin.            8
unemployed        6
management        6
entrepreneur      3
self-employed     2
retired           2
housemaid         2
unknown           1
Name: count, dtype: int64

In [53]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('blue-collar')

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44928 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [55]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [56]:
married_tertiary_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [57]:
married_tertiary_failure_yes['Job'].value_counts()

Job
management       23
technician        8
admin.            4
self-employed     2
entrepreneur      1
student           1
unemployed        1
housemaid         1
Name: count, dtype: int64

In [58]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('management')

In [59]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44940 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [60]:
married_null_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [61]:
married_null_failure_yes['Job'].value_counts()

Job
admin.           7
management       5
technician       4
blue-collar      4
unemployed       2
entrepreneur     2
housemaid        2
services         2
self-employed    1
Name: count, dtype: int64

In [62]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('admin.')

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44952 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [64]:
married_unknown_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [65]:
married_unknown_failure_yes['Job'].value_counts()

Job
management    1
student       1
admin.        1
Name: count, dtype: int64

In [66]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('student')

In [67]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44953 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [68]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [69]:
married_primary_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [70]:
married_primary_failure_yes['Job'].value_counts()

Job
blue-collar    6
services       2
management     1
housemaid      1
retired        1
Name: count, dtype: int64

In [71]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('blue-collar')

In [72]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44957 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [73]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [229]:
married_secondary_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [231]:
married_secondary_other_yes['Job'].value_counts()

Job
blue-collar    6
technician     5
admin.         5
retired        1
management     1
Name: count, dtype: int64

In [233]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('blue-collar')

In [235]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44962 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [55]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [237]:
married_tertiary_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [239]:
married_tertiary_other_yes['Job'].value_counts()

Job
management       11
technician        3
entrepreneur      1
self-employed     1
Name: count, dtype: int64

In [241]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('management')

In [243]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44973 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [245]:
married_null_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [247]:
married_null_other_yes['Job'].value_counts()

Job
management       6
blue-collar      5
admin.           4
technician       3
self-employed    2
services         1
housemaid        1
Name: count, dtype: int64

In [249]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('management')

In [251]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44975 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [253]:
married_unknown_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [255]:
married_unknown_other_yes['Job'].value_counts()

Job
services      1
management    1
Name: count, dtype: int64

In [257]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('services')

In [259]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44976 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [68]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [261]:
married_primary_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [263]:
married_primary_other_yes['Job'].value_counts()

Job
blue-collar     2
entrepreneur    1
technician      1
Name: count, dtype: int64

In [265]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('blue-collar')

In [267]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44976 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [269]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [271]:
married_primary_success_yes=pd.DataFrame(data.loc[(data['Marital Status']=='married') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='success')])

In [273]:
married_primary_success_yes['Job'].value_counts()

Job
management     3
blue-collar    3
unknown        1
retired        1
services       1
technician     1
Name: count, dtype: int64

In [275]:
data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='success'),'Job']=data.fillna('management')

In [277]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            44978 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [281]:
data['Marital Status'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [283]:
divorced_secondary_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [285]:
divorced_secondary_unknown_yes['Job'].value_counts()

Job
admin.           24
technician       13
services         11
management        3
blue-collar       3
self-employed     2
housemaid         2
unemployed        1
retired           1
entrepreneur      1
Name: count, dtype: int64

In [287]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('admin.')

In [289]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45002 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [291]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [293]:
divorced_tertiary_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [295]:
divorced_tertiary_unknown_yes['Job'].value_counts()

Job
management       27
technician        7
entrepreneur      3
self-employed     3
unemployed        2
admin.            2
retired           1
Name: count, dtype: int64

In [297]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('management')

In [299]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45018 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [301]:
divorced_null_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [303]:
divorced_null_unknown_yes['Job'].value_counts()

Job
management       13
blue-collar       4
services          4
technician        4
admin.            3
retired           2
housemaid         2
self-employed     1
entrepreneur      1
unemployed        1
Name: count, dtype: int64

In [305]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('management')

In [307]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45037 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [309]:
divorced_unknown_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [311]:
divorced_unknown_unknown_yes['Job'].value_counts()

Job
blue-collar     2
technician      2
services        1
admin.          1
entrepreneur    1
Name: count, dtype: int64

In [313]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('blue-collar')

In [315]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45037 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [317]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [319]:
divorced_primary_unknown_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown')])

In [321]:
divorced_primary_unknown_yes['Job'].value_counts()

Job
blue-collar    19
unemployed      2
technician      1
retired         1
Name: count, dtype: int64

In [323]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='unknown'),'Job']=data.fillna('blue-collar')

In [325]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45038 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [27]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [327]:
divorced_secondary_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [329]:
divorced_secondary_null_yes['Job'].value_counts()

Job
technician       8
unemployed       5
services         5
admin.           5
blue-collar      3
self-employed    1
Name: count, dtype: int64

In [331]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('technician')

In [333]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45049 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [335]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [337]:
divorced_tertiary_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [339]:
divorced_tertiary_null_yes['Job'].value_counts()

Job
management       17
retired           3
entrepreneur      2
services          2
unemployed        1
technician        1
self-employed     1
Name: count, dtype: int64

In [341]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('management')

In [343]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45055 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [345]:
divorced_null_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [347]:
divorced_null_null_yes['Job'].value_counts()

Job
admin.          5
management      4
retired         4
blue-collar     3
technician      3
unemployed      2
services        1
entrepreneur    1
Name: count, dtype: int64

In [349]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('admin.')

In [351]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45062 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [353]:
divorced_unknown_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [355]:
divorced_unknown_null_yes['Job'].value_counts()

Job
unemployed    1
technician    1
Name: count, dtype: int64

In [357]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('unemployed')

In [359]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45062 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [361]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [363]:
divorced_primary_null_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull())])

In [365]:
divorced_primary_null_yes['Job'].value_counts()

Job
blue-collar      2
self-employed    1
retired          1
housemaid        1
Name: count, dtype: int64

In [367]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign'].isnull()),'Job']=data.fillna('blue-collar')

In [369]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45063 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [371]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [373]:
divorced_secondary_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [375]:
divorced_secondary_failure_yes['Job'].value_counts()

Job
technician      4
admin.          3
services        2
blue-collar     1
entrepreneur    1
retired         1
Name: count, dtype: int64

In [377]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('technician')

In [379]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45067 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [381]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [383]:
divorced_tertiary_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [385]:
divorced_tertiary_failure_yes['Job'].value_counts()

Job
management    2
admin.        1
technician    1
Name: count, dtype: int64

In [387]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('management')

In [389]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45070 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [391]:
divorced_null_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [393]:
divorced_null_failure_yes['Job'].value_counts()

Job
management    2
admin.        1
Name: count, dtype: int64

In [395]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('management')

In [397]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45070 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [399]:
divorced_unknown_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [401]:
divorced_unknown_failure_yes['Job'].value_counts()

Job
services    1
Name: count, dtype: int64

In [403]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('services')

In [405]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45072 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [407]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [409]:
divorced_primary_failure_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure')])

In [411]:
divorced_primary_failure_yes['Job'].value_counts()

Job
blue-collar    2
Name: count, dtype: int64

In [413]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='failure'),'Job']=data.fillna('blue-collar')

In [415]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45072 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [417]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [419]:
divorced_secondary_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='secondary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [421]:
divorced_secondary_other_yes['Job'].value_counts()

Job
admin.        1
services      1
retired       1
technician    1
Name: count, dtype: int64

In [423]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='secondary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('services')

In [425]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45074 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [427]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [429]:
divorced_tertiary_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='tertiary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [431]:
divorced_tertiary_other_yes['Job'].value_counts()

Job
management       4
self-employed    1
Name: count, dtype: int64

In [433]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='tertiary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('management')

In [435]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45076 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [437]:
divorced_null_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification'].isnull()) & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [439]:
divorced_null_other_yes['Job'].value_counts()

Job
admin.        2
technician    1
services      1
management    1
Name: count, dtype: int64

In [441]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification'].isnull()) & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('admin.')

In [443]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45078 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [445]:
divorced_unknown_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='unknown') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [447]:
divorced_unknown_other_yes['Job'].value_counts()

Series([], Name: count, dtype: int64)

In [257]:
'''data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='unknown') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('services')
 '''

In [449]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45078 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [68]:
data['Educational Qualification'].unique()

array(['tertiary', 'secondary', nan, 'unknown', 'primary'], dtype=object)

In [451]:
divorced_primary_other_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other')])

In [453]:
divorced_primary_other_yes['Job'].value_counts()

Series([], Name: count, dtype: int64)

In [265]:
'''data.loc[(data['Marital Status']=='married') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('blue-collar')'''

In [455]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45078 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [269]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [457]:
divorced_primary_success_yes=pd.DataFrame(data.loc[(data['Marital Status']=='divorced') & (data['Educational Qualification']=='primary') & (data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='success')])

In [459]:
divorced_primary_success_yes['Job'].value_counts()

Job
blue-collar    1
admin.         1
Name: count, dtype: int64

In [461]:
data.loc[(data['Marital Status']=='divorced') & 
(data['Educational Qualification']=='primary') & 
(data['Subscription Status']=='yes')
 & (data['Age'].between(31,56)) & (data['Outcome Of Previous Marketing Campaign']=='success'),'Job']=data.fillna('admin.')

In [463]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45080 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [465]:
data['Outcome Of Previous Marketing Campaign'].unique()

array([nan, 'unknown', 'failure', 'other', 'success'], dtype=object)

In [469]:
data.loc[data['Job'].isnull()]

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category
25516,45,NaN,divorced,secondary,cellular,19,nov,NaN,1,success,yes,41-45
26061,40,NaN,married,tertiary,cellular,19,nov,639.0,2,success,yes,36-40
31617,37,NaN,married,secondary,telephone,6,apr,1353.0,2,success,yes,36-40
32542,32,NaN,divorced,tertiary,cellular,17,NaN,NaN,1,success,yes,31-35
33878,48,NaN,married,secondary,cellular,30,apr,NaN,1,success,yes,46-50
...,...,...,...,...,...,...,...,...,...,...,...,...
45003,42,NaN,married,unknown,cellular,19,oct,230.0,1,success,yes,41-45
45017,52,NaN,married,secondary,cellular,21,oct,453.0,1,success,yes,51-55
45103,44,NaN,married,tertiary,cellular,9,nov,248.0,1,success,yes,41-45
45108,35,NaN,married,secondary,cellular,9,nov,524.0,1,success,yes,31-35
45126,34,NaN,married,secondary,cellular,12,nov,413.0,1,success,yes,31-35

In [475]:
data.loc[(data['Subscription Status']=='yes') & (data['Outcome Of Previous Marketing Campaign']=='success')]['Job'].value_counts()

Job
management       174
retired          111
admin.            80
technician        76
student           69
blue-collar       54
services          30
unemployed        25
self-employed     20
housemaid          8
entrepreneur       6
unknown            3
Name: count, dtype: int64

In [477]:
data.loc[(data['Subscription Status']=='yes') & (data['Outcome Of Previous Marketing Campaign']=='success'),'Job']=data.fillna('management')

In [479]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45158 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [481]:
data.loc[data['Job'].isnull()]

,Age,Job,Marital Status,Educational Qualification,Contact Communication type,Last Contact Day Of The Month,Last Contact Month Of The Year,Contact Duration (Seconds),No Of Contacts Performed During This Campaign,Outcome Of Previous Marketing Campaign,Subscription Status,Age_Category
35469,49,NaN,single,primary,cellular,7,may,1516.0,2,other,yes,46-50

In [485]:
data.loc[(data['Subscription Status']=='yes') & (data['Outcome Of Previous Marketing Campaign']=='other'),'Job']=data.fillna('management')

In [487]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45159 entries, 0 to 45158
Data columns (total 12 columns):
 #   Column                                         Non-Null Count  Dtype
---  ------                                         --------------  -----
 0   Age                                            45159 non-null  int64
 1   Job                                            45159 non-null  object
 2   Marital Status                                 45159 non-null  object
 3   Educational Qualification                      33861 non-null  object
 4   Contact Communication type                     45159 non-null  object
 5   Last Contact Day Of The Month                  45159 non-null  int64
 6   Last Contact Month Of The Year                 33862 non-null  object
 7   Contact Duration (Seconds)                     33908 non-null  float64
 8   No Of Contacts Performed During This Campaign  45159 non-null  int64
 9   Outcome Of Previous Marketing Campaign         33866 non-null  object
 10  Subscription Status                            45159 non-null  object
 11  Age_Category                                   45159 non-null  object
dtypes: float64(1), int64(3), object(8)
memory usage: 4.1+ MB

In [491]:
data.to_csv('Transformed_data.csv')